apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          env:
            - name: {{ .Values.env.urlName }}
              value: {{ .Values.env.urlValue }}
          ports:
            - containerPort: {{ .Values.targetPort }}