kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.container.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumne.storage }}
  storageClassName: {{ .Values.container.namespace }}
