kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.container.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    app: {{ .Values.app }}
  clusterIP: None
  ports:
    - port: {{ .Values.ports.rest.port }}
      name: {{ .Values.ports.rest.name }}
    - port: {{ .Values.ports.interNode.port }}
      name: {{ .Values.ports.interNode.name }}
